// <auto-generated />
using BookClub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookClub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookClub.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice.smith@mail.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            Password = "123456",
                            Username = "alice_smith"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob.jones@mail.com",
                            FirstName = "Bob",
                            LastName = "Jones",
                            Password = "123456",
                            Username = "bob_jones"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie.brown@mail.com",
                            FirstName = "Charlie",
                            LastName = "Brown",
                            Password = "123456",
                            Username = "charlie_brown"
                        },
                        new
                        {
                            Id = 4,
                            Email = "diana.white@mail.com",
                            FirstName = "Diana",
                            LastName = "White",
                            Password = "123456",
                            Username = "diana_white"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ella.green@mail.com",
                            FirstName = "Ella",
                            LastName = "Green",
                            Password = "123456",
                            Username = "ella_green"
                        });
                });

            modelBuilder.Entity("BookClub.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Ava Miles",
                            Description = "A suspenseful thriller set in an eerie town.",
                            ISBN = "9780451491234",
                            Title = "The Silent Library"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Liam Frost",
                            Description = "A poetic journey through forgotten landscapes.",
                            ISBN = "9780143110433",
                            Title = "Gardens of Glass"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Elena Brook",
                            Description = "A tale of lost civilizations and secret histories.",
                            ISBN = "9780670022450",
                            Title = "Moonlight Archive"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Mason Quinn",
                            Description = "A gritty sci-fi about survival on a dying planet.",
                            ISBN = "9780316095839",
                            Title = "Echoes of Dust"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Harper Lee",
                            Description = "Short stories and memories from a reclusive writer.",
                            ISBN = "9780061120084",
                            Title = "Notes from the Attic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
